[FIX] sale_product_pack: fix error when creating Down Payment
acsone/product-pack pull request #1
Opened 2023-03-28 15:08 UTC by augusto-weiss

Error Traceback:
 `Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1808, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 149, in create_invoices
    self._create_invoices(self.sale_order_ids)
  File "/opt/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 177, in _create_invoices
    self.env['sale.order.line'].create(
  File "<decorator-gen-215>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/mnt/data/odoo-addons-dir/sale_product_pack/models/sale_order_line.py", line 81, in create
    product = self.env["product.product"].browse(elem["product_id"])
KeyError: 'product_id'`

TO REPLAY:
* Create a sale order and confirm
* From sale order, press Create Invoice
* Select Create Down Payment

![image](https://user-images.githubusercontent.com/90717087/228282921-5079da63-4f2c-4256-a0f2-24ab0ccab327.png)

2023-03-28 15:10 UTC, augusto-weiss commented
Hi @FrancoMaxime !!
Here is an error that we could detect and we added a little fix to avoid this error!

2023-03-29 09:41 UTC, FrancoMaxime requested changes

2023-03-29 09:41 UTC, FrancoMaxime commented on sale_product_pack/models/sale_order_line.py
> +            )
I think that could be improved like this, what do you think of this?
```suggestion
            product = self.env["product.product"].browse(elem.get("product_id"))
```

2023-03-29 09:45 UTC, FrancoMaxime commented on sale_product_pack/models/sale_order_line.py
> +            )
Hi @augusto-weiss, i forgot to mention you during my review. Thanks for the bug fix, maybe you could review the initial pull request, maybe i made others mistakes, i hope not.

2023-03-30 19:30 UTC, augusto-weiss commented
Hi @FrancoMaxime  i commited your suggestion!! I'll review your pr!! Thanks

2023-03-31 06:35 UTC, FrancoMaxime commented
@augusto-weiss Hi, can you regroup the two commit into the first one? That's better for the OCA repository

2023-03-31 12:06 UTC, augusto-weiss commented
Done @FrancoMaxime

2023-03-31 13:48 UTC, merged